from parser import (
    Program, VarDecl, Assignment, TypeCastAssignment, TypeOnlyAssignment,
    Gimmeh, Print, IfStmt, Loop, SwitchCase, ImplicitIT,
    Expression, Literal, VarRef,
    FunctionDef, FunctionCall, ReturnStmt, BreakStmt
)
# These are the node types generated by the parser.
# They represent the structure of the LOLCODE program (the Abstract Syntax Tree or AST).

import sys

class LOLRuntimeError(Exception):
    """
    Custom exception class for errors encountered during program execution (runtime).
    This helps distinguish interpreter errors from standard Python exceptions.
    """
    pass


# === || Environment || ===
class Environment:
    """
    Manages the scope/context for variables. It supports nested scopes (like function calls).
    This implements the **Lexical Scoping** rule.
    """
    def __init__(self, parent=None):
        # Dictionary to hold variables in the current scope.
        # Format: {variable_name: {"type": "...", "value": ...}}
        self.vars = {}
        # Reference to the outer/enclosing scope (used for nested function/block access).
        self.parent = parent

    def define(self, name, value):
        """
        Declares a new variable in the *current* scope.
        Used for initial declarations (e.g., I HAS A X).
        """
        self.vars[name] = value

    def set(self, name, value):
        """
        Assigns a new value to an *existing* variable.
        It searches up the scope chain (parent environments) to find where the variable was defined.
        Used for assignments (e.g., X R 10).
        """
        env = self.lookup_env(name)
        if env is None:
            # Variable must exist to be set.
            raise LOLRuntimeError(f"Variable '{name}' not declared.")
        env.vars[name] = value

    def get(self, name):
        """
        Retrieves the value of a variable, searching up the scope chain.
        """
        env = self.lookup_env(name)
        if env is None:
            # Variable must exist to be retrieved.
            raise LOLRuntimeError(f"Variable '{name}' not declared.")
        return env.vars[name]

    def lookup_env(self, name):
        """
        **Scope Resolution:** Searches for the environment object that contains the variable 'name'.
        It starts at the current environment and recursively checks the 'parent' until the global scope is reached.
        """
        env = self
        while env:
            if name in env.vars:
                return env
            env = env.parent # Move to the parent scope
        return None # Variable not found in any scope


# ---

# === || Interpreter || ===
class Interpreter:
    """
    The main engine for executing the LOLCODE program represented by the AST.
    It traverses the AST and performs the actions defined by each node.
    """
    def __init__(self, ast: Program):
        self.ast = ast # The entire program's AST root node.
        self.global_env = Environment() # The outermost scope for global variables.
        self.functions = {} # Stores FunctionDef nodes, indexed by function name.
        # The 'It' variable (Implicit IT), which holds the result of the last evaluation.
        # Initialized to the 'NOOB' value.
        self.IT = {"type": "NOOB", "value": None}

    # Use this to run the interpreter in main
    def run(self):
        """
        Initializes and starts the execution of the LOLCODE program.
        """
        # load globals (var decls in WAZZUP)
        # Global variable declarations (I HAS A) are processed first.
        for d in self.ast.declarations:
            self.eval(d, self.global_env)

        # register function definitions
        # Function definitions (HOW DUZ I) are stored for later calls, not executed yet.
        for fn in self.ast.functions:
            self.functions[fn.name] = fn

        print("Registered functions:", list(self.functions.keys()))

        # run main (skip function defs)
        # Execute the main program statements.
        for stmt in self.ast.statements:
            self.eval(stmt, self.global_env)

    # === || Eval Dispatcher || ===
    def eval(self, node, env):
        """
        **The core execution method.**
        It takes an AST node and the current Environment, determines the node's type,
        and dispatches the evaluation to the appropriate handler method.
        """
        if isinstance(node, VarDecl):
            return self.eval_var_decl(node, env)
        if isinstance(node, Assignment):
            return self.eval_assignment(node, env)
        # ... (other assignment/type cast handlers) ...
        if isinstance(node, Gimmeh):
            return self.eval_gimmeh(node, env)
        if isinstance(node, Print):
            return self.eval_print(node, env)
        if isinstance(node, Expression):
            return self.eval_expr(node, env)
        if isinstance(node, Literal):
            # Converts raw literal values (e.g., "HAI", 123, 4.5) into the internal
            # LOLCODE type/value representation (e.g., {"type": "YARN", "value": "HAI"}).
            return self.cast_literal(node.value)
        if isinstance(node, VarRef):
            # Variable lookup
            if node.name == "IT": # for implicit IT
                return self.IT # IT is a special, interpreter-managed variable.
            return env.get(node.name) # Get value from environment.
        if isinstance(node, IfStmt):
            return self.eval_if(node, env)
        if isinstance(node, Loop):
            return self.eval_loop(node, env)
        if isinstance(node, SwitchCase):
            return self.eval_switch(node, env)
        if isinstance(node, FunctionDef):
            # Function definitions are handled in `run`, here they just return None.
            return None
        if isinstance(node, FunctionCall):
            return self.eval_call(node, env)
        if isinstance(node, ReturnStmt):
            # Special return value format used to signal a function exit and the return value.
            return ("RETURN", self.eval(node.value, env))
        if isinstance(node, BreakStmt):
            # Special return value format used to signal an early loop exit.
            return ("BREAK", None)
        if isinstance(node, ImplicitIT):
            # A reference to the special variable IT, like in O RLY?
            return self.IT

        raise LOLRuntimeError("Unhandled AST node type: " + str(type(node)))

    # ---

    # # === || Variable Declaration || ===
    def eval_var_decl(self, node, env):
        """
        Handles 'I HAS A' declarations.
        Initializes the variable in the current environment. If no initial value, it's 'NOOB'.
        """
        if node.init is None:
            # Default initialization to NOOB (no value).
            env.define(node.name, {"type": "NOOB", "value": None})
        else:
            # Evaluate the initial value expression and define the variable.
            val = self.eval(node.init, env)
            env.define(node.name, val)

    # === || Assignment || ===
    def eval_assignment(self, node, env):
        """
        Handles standard assignments (e.g., 'X R SUM OF 1 2').
        """
        val = self.eval(node.value, env) # Evaluate the right-hand side.
        env.set(node.target, val)       # Store the value in the environment (updates scope).
        self.IT = val                   # Update the 'It' variable (Implicit IT).

    def eval_type_cast_assignment(self, node, env):
        """
        Handles type casting assignment (e.g., 'Y R MAEK X A NUMBR').
        Retrieves the source variable, casts it, stores the result, and updates IT.
        """
        val = env.get(node.source)
        casted = self.typecast(val, node.target_type)
        env.set(node.target, casted)
        self.IT = casted

    def eval_type_only_assignment(self, node, env):
        """
        Handles in-place type casting (e.g., 'MAEK X A NUMBR').
        Retrieves the variable, casts its type, and updates the variable and IT.
        """
        var = env.get(node.target)
        casted = self.typecast(var, node.new_type)
        env.set(node.target, casted)
        self.IT = casted

    # === || Input (Gimmeh) || ===
    def eval_gimmeh(self, node, env):
        """
        Handles the 'GIMMEH' command, reading a line from standard input.
        The input is *always* stored as a YARN (string).
        """
        raw = input()     # Reads from stdin.
        # Sets the target variable to the YARN type/value.
        env.set(node.target, {"type": "YARN", "value": raw})
        self.IT = {"type": "YARN", "value": raw}

    # === || Print || ===
    def eval_print(self, node, env):
        """
        Handles the 'VISIBLE' command.
        Evaluates all operands and concatenates their YARN (string) representations.
        """
        out = ""
        for op in node.operands:
            val = self.eval(op, env)          # Evaluate the expression/variable.
            out += self.to_yarn(val)          # Convert the result to a string (YARN).
        print(out)                          # Print the result to stdout.
        self.IT = {"type": "YARN", "value": out} # The result of a VISIBLE is a YARN in IT.

    # ---

    # === || Expressions & Operators || ===
    def eval_expr(self, node, env):
        """
        Evaluates a general expression node (e.g., 'SUM OF', 'BOTH OF', 'SMOOSH').
        """
        op = node.op

        # unary (single operand)
        if op == "NOT":
            v = self.eval(node.operands[0], env)
            # Apply logical NOT after converting the operand to a boolean (TROOF).
            return {"type": "TROOF", "value": not self.to_bool(v)}

        # infinite arity (any number of operands)
        if op == "SMOOSH":
            parts = []
            for o in node.operands:
                # Evaluate, then convert to YARN, then append to list of parts.
                parts.append(self.to_yarn(self.eval(o, env)))
            # Concatenate all parts into a single YARN.
            return {"type": "YARN", "value": "".join(parts)}

        # binary math (two operands)
        if op in ("SUM_OF", "DIFF_OF", "PRODUKT_OF", "QUOSHUNT_OF", "MOD_OF",
        "BIGGR_OF", "SMALLR_OF"):
            a = self.eval(node.operands[0], env)
            b = self.eval(node.operands[1], env)
            return self.math_eval(op, a, b) # Delegate to math evaluation helper.

        # binary boolean (two operands)
        if op in ("BOTH_OF", "EITHER_OF", "WON_OF"):
            a = self.eval(node.operands[0], env)
            b = self.eval(node.operands[1], env)
            return self.bool_eval(op, a, b) # Delegate to boolean evaluation helper.

        # n-ary boolean (one or more operands)
        if op in ("ALL_OF", "ANY_OF"):
            # Evaluate all operands first, then pass the results to the helper.
            return self.multi_bool_eval(op, [self.eval(x, env) for x in node.operands])

        # comparison (two operands)
        if op in ("BOTH_SAEM", "DIFFRINT"):
            a = self.eval(node.operands[0], env)
            b = self.eval(node.operands[1], env)
            return self.compare_eval(op, a, b) # Delegate to comparison evaluation helper.

        raise LOLRuntimeError(f"Unknown operator {op}")

    # === || Math Operators || ===
    def math_eval(self, op, a, b):
        """
        Performs arithmetic and comparison operations.
        Inputs are automatically cast to the appropriate number type (NUMBR/NUMBAR) before the operation.
        """
        ax = self.to_number(a) # Convert operand A to a native Python number (int/float).
        bx = self.to_number(b) # Convert operand B to a native Python number (int/float).

        # ... (python math logic) ...

        # Decide NUMBR vs NUMBAR
        # The result type in LOLCODE depends on the final value's characteristics.
        if isinstance(res, float) and not res.is_integer():
            return {"type": "NUMBAR", "value": float(res)} # Floating-point result
        # integer result
        if float(res).is_integer():
            return {"type": "NUMBR", "value": int(res)}    # Integer result
        # fallback (shouldn't be strictly necessary if all paths covered)
        return {"type": "NUMBAR", "value": float(res)}

    # === || Boolean || ===
    def bool_eval(self, op, a, b):
        """
        Handles binary logical operators (AND, OR, XOR).
        Inputs are automatically cast to TROOF (boolean) before the operation.
        """
        A = self.to_bool(a) # Convert operand A to Python boolean.
        B = self.to_bool(b) # Convert operand B to Python boolean.

        if op == "BOTH_OF":
            return {"type": "TROOF", "value": A and B} # Logical AND
        if op == "EITHER_OF":
            return {"type": "TROOF", "value": A or B}  # Logical OR
        if op == "WON_OF":
            return {"type": "TROOF", "value": A ^ B}   # Logical XOR (using Python's bitwise XOR for booleans)

    def multi_bool_eval(self, op, vals):
        """
        Handles n-ary logical operators (ALL OF, ANY OF).
        """
        bs = [self.to_bool(v) for v in vals] # Convert all operands to Python booleans.
        if op == "ALL_OF":
            return {"type": "TROOF", "value": all(bs)} # True if all are True.
        if op == "ANY_OF":
            return {"type": "TROOF", "value": any(bs)} # True if any are True.

    # === || Comparison || ===
    def compare_eval(self, op, a, b):
        """
        Handles comparison operators (BOTH SAEM, DIFFRINT).
        NOTE: LOLCODE comparison is strict: types MUST match for values to be compared.
        """
        # direct type match only
        if a["type"] != b["type"]:
            # If types don't match, they are considered different.
            return {"type": "TROOF", "value": (op == "DIFFRINT")}

        same = (a["value"] == b["value"]) # Compare the raw Python values.
        if op == "BOTH_SAEM":
            return {"type": "TROOF", "value": same}
        else: # DIFFRINT
            return {"type": "TROOF", "value": not same}

    # === || If / O RLY? || ===
    def eval_if(self, node, env):
        """
        Handles 'O RLY?' (If-Else) statements.
        The condition is taken from IT by default, or an optional expression.
        """
        # The condition is implicitly IT if not provided.
        cond = self.IT if node.condition is None else self.eval(node.condition, env)

        if self.to_bool(cond):
            # Execute the 'YA RLY' block.
            return self.eval_block(node.ya_block, env)
        if node.nowai_block:
            # Execute the 'NO WAI' block.
            return self.eval_block(node.nowai_block, env)
        # Note: ELIF/MEBBE blocks are often handled within the AST for `ya_block` by the parser.
        # This implementation simplifies it to just a YA RLY / NO WAI structure.

    # === || Loop || ===
    def eval_loop(self, node, env):
        """
        Handles 'IM IN YR'/'IM OUTTA YR' loops.
        """
        while True:
            # condition check
            if node.condition:
                cond = self.eval(node.condition, env)
                should_continue = self.to_bool(cond)

                if node.mode == "TIL":
                    # Loop 'TIL' (until) a condition is TRUE.
                    should_continue = not should_continue
                elif node.mode == "WILE":
                    # Loop 'WILE' (while) a condition is TRUE.
                    pass # already set by to_bool(cond)

                if not should_continue:
                    break

            # body
            # Execute statements in the loop body.
            for stmt in node.body:
                res = self.eval(stmt, env)
                # Check for an explicit loop exit command (BreakStmt/GTFO).
                if isinstance(res, tuple) and res[0] == "BREAK":
                    return # Exit the loop evaluation.

            # update iterator (if an iterator variable is defined)
            if node.iterator:
                # Get the current numeric value of the iterator.
                v = self.to_number(env.get(node.iterator))
                if node.mode == "UPPIN":
                    v += 1 # Increment (UPPIN YR).
                elif node.mode == "NERFIN":
                    v -= 1 # Decrement (NERFIN YR).
                # Update the variable in the environment.
                env.set(node.iterator, {"type": "NUMBR", "value": v})

    # === || Switch / WTF? || ===
    def eval_switch(self, node, env):
        """
        Handles 'WTF?' (Switch-Case) statements.
        It compares the value of IT against the literal values in the cases.
        """
        it_val = self.IT # The value of IT is the switch expression.

        for lit, body in node.cases:
            case_val = self.eval(lit, env) # Evaluate the literal value for the case.
            # Compare the case value against IT's value.
            if case_val["value"] == it_val["value"]:
                return self.eval_block(body, env) # Execute the case body.

        if node.default:
            # Execute the 'OMGWTF' (default) block if no case matched.
            return self.eval_block(node.default, env)

    # === || Function call || ===
    def eval_call(self, node, env):
        """
        Handles 'I IZ' function calls.
        Creates a new scope, binds parameters, executes the body, and handles the return value.
        """
        f = self.functions.get(node.name) # Look up the FunctionDef AST node.
        if f is None:
            raise LOLRuntimeError(f"Function {node.name} not found.")

        # new local scope: Create a new environment for the function call.
        # Its parent is the global environment (LOLCODE uses static/global scoping).
        call_env = Environment(parent=self.global_env)

        # evaluate args and bind parameters
        if len(node.args) != len(f.params):
            raise LOLRuntimeError("Argument count mismatch.")

        for param, arg_expr in zip(f.params, node.args):
            # Evaluate each argument in the *caller's* environment (`env`)
            # and define it as a parameter in the *function's* environment (`call_env`).
            call_env.define(param, self.eval(arg_expr, env))

        # execute body
        for stmt in f.body:
            res = self.eval(stmt, call_env) # Execute statement in the new local scope.
            # Check for a return command (ReturnStmt/FOUND).
            if isinstance(res, tuple) and res[0] == "RETURN":
                self.IT = res[1] # Set IT to the return value.
                return res[1]    # Return the value back to the caller.

        # no FOUND was encountered (implicit return)
        self.IT = {"type": "NOOB", "value": None} # IT becomes NOOB.
        return self.IT # Implicitly returns NOOB.

    # === || Helpers || ===
    def eval_block(self, block, env):
        """
        Executes a sequence of statements (a block), such as a function body or IF branch.
        Stops and returns immediately if a control flow instruction (RETURN/BREAK) is encountered.
        """
        for stmt in block:
            res = self.eval(stmt, env)
            if isinstance(res, tuple):
                # This is a control flow signal (RETURN or BREAK). Pass it up.
                return res

    def cast_literal(self, v):
        """
        Converts a raw string/number value from the parser into the internal LOLCODE object structure.
        """
        # YARN (string literal, e.g., "Hello")
        if v.startswith('"'):
            return {"type": "YARN", "value": v.strip('"')}
        # TROOF (boolean literal, WIN/FAIL or TRUE/FALSE)
        if v.upper() in ("WIN", "FAIL", "TRUE", "FALSE"):
            return {"type": "TROOF", "value": (v.upper() in ("WIN", "TRUE"))}
        # NUMBAR (float/decimal literal, e.g., 12.3)
        if "." in v:
            return {"type": "NUMBAR", "value": float(v)}
        # NUMBR (integer literal, e.g., 123)
        return {"type": "NUMBR", "value": int(v)}

    def to_bool(self, val):
        """
        Converts any LOLCODE value to a TROOF (boolean), following LOLCODE type-casting rules.
        - NOOB, FAIL, 0, "" are FAIL (False).
        - Everything else is WIN (True).
        """
        t, v = val["type"], val["value"]
        if t == "NOOB":
            return False
        if t == "TROOF":
            return v
        if t in ("NUMBR", "NUMBAR"):
            return v != 0
        if t == "YARN":
            return v != ""
        return False

    def to_number(self, val):
        """
        Converts any LOLCODE value to a NUMBR or NUMBAR (number), following LOLCODE type-casting rules.
        - TROOF -> 1 (WIN) or 0 (FAIL).
        - NOOB -> 0.
        - YARN -> Must be a valid numeric string or raises an error.
        """
        # ... (conversion logic) ...

        if t == "YARN":
            s = str(v).strip()
            # YARN must be numeric-looking or error
            try:
                # Check for float (NUMBAR)
                if '.' in s:
                    return float(s)
                # Assume integer (NUMBR)
                return int(s)
            except ValueError:
                raise LOLRuntimeError(f"Cannot cast YARN '{s}' to number.")

        raise LOLRuntimeError(f"Cannot convert {t} to number.")

    def to_yarn(self, val):
        """
        Converts any LOLCODE value to a YARN (string) for printing or concatenation.
        - TROOF -> "WIN" or "FAIL".
        - NOOB -> "".
        - NUMBR/NUMBAR -> String representation.
        """
        t = val["type"]
        v = val["value"]

        if t == "TROOF":
            return "WIN" if v == True else "FAIL"

        if v is None:
            # Handles NOOB type
            return ""

        return str(v)

    def typecast(self, val, t):
        """
        Placeholder for the explicit type-casting logic (MAEK).
        TODO: Currently a shallow placeholder. Needs to implement the actual conversion rules.
        """
        # TODO: implement explicit MAEK semantics
        # For a full implementation, this should call the specific to_bool, to_number, or to_yarn logic
        # depending on the target type 't'.
        return {"type": t, "value": val["value"]} # This currently only changes the type tag, not the value.